language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  - pip install .
script:
  - python -m pytest --cov-report=xml --cov=samesyslib tests

after_success:
  - codecov

deploy:
  provider: pypi
  user: __token__
  password: $TEST_PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master